//
//  CreateProfileMailInteractor.swift
//  OC12-CleanNetworkBox
//
//  Created by Walim Aloui on 16/08/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateProfileMailBusinessLogic
{
  func doSomething(request: CreateProfileMail.Something.Request)
}

protocol CreateProfileMailDataStore
{
  //var name: String { get set }
}

class CreateProfileMailInteractor: CreateProfileMailBusinessLogic, CreateProfileMailDataStore
{
  var presenter: CreateProfileMailPresentationLogic?
  var worker: CreateProfileMailWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: CreateProfileMail.Something.Request)
  {
    worker = CreateProfileMailWorker()
    worker?.doSomeWork()
    
    let response = CreateProfileMail.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
