version: 2.1

jobs:
  build-and-test:
    macos:
      xcode: 14.3.1
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: register_app
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - run:
          name: Run tests
          command: |
            xcodebuild clean build test -project OC12-CleanNetworkBox.xcodeproj -scheme OC12-CleanNetworkBox -destination 'platform=iOS Simulator,OS=15.0,name=iPhone 13'
workflows:  
  build-and-test:
    jobs:
      - build-and-test
