version: 2.1

jobs:
  build:
    macos:
      xcode: 14.3.1
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_APP_IDENTIFIER: "adpiscinam.OC12-CleanNetworkBox"
      FASTLANE_APPLE_ID: "contact@walimaloui.com"
      FASTLANE_TEAM_ID: "S25TANK5XP"
      
    steps:
      - checkout
      - run:
            name: Clean Workspace
            command: rm -rf ~/.rvm ~/.rbenv /usr/local/rvm /usr/local/bin/rbenv
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane register_app --verbose

  #tests:
 #   steps:
  #    - run:
  #        name: Run tests
   #       command: bundle exec fastlane run_unit_test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
  #    - tests
