//
//  CreateProfileMailModels.swift
//  OC12-CleanNetworkBox
//
//  Created by Walim Aloui on 16/08/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CreateProfileEmail {
    
    enum Email {
        struct Request {
            var email: String?
        }
    }
}
