default_platform(:ios)

platform :ios do
    before_all do
        setup_circle_ci
    end

    lane :run_unit_test do
        scan
    end

    lane :register_app do
       produce
    end

    lane :get_dev_certs do
       cert(development: true)
       sigh(development: true)
    end
end
